name: 打包小林工具箱

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置 Python
      uses: actions/setup-python@v5  # 改成 v5，不是 v5.0
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        pip install pyinstaller
        pip install pillow
    
    - name: 打包成 exe
      run: |
        pyinstaller -F --icon="icon.ico" --name="XiaoLinToolbox" code/main.py
    
    - name: 上传 exe 文件
      uses: actions/upload-artifact@v4
      with:
        name: XiaoLinToolbox-Windows
        path: dist/*.exe